spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/${db.name}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server:
  servlet:
    context-path: /api

cluster:
  hosts:
    0:
      - 'app-node3:'
      - 'app-node6:'
      - 'app-node9:'
    1:
      - 'app-node1:'
      - 'app-node4:'
      - 'app-node7:'
    2:
      - 'app-node2:'
      - 'app-node5:'
      - 'app-node8:'